### PR TITLE
Fix for game over

### PR DESCRIPTION
**Pull request by TTsdzb**
The plugin still not triggers game-over properly when guess over 6 times. This should fix the problem on some platforms, and return the right message.

### CODE REVIEW

**Review by MaikoTan — APPROVED** [review]
LGTM

**Comment by MaikoTan** [comment]
@Lipraty What do you think?

**Comment by Lipraty** [comment]
Look good to me. Lint errors need to be ignored though?

**Review by Lipraty — APPROVED** [review]

**Comment by Lipraty** [comment]
fine

**Comment by TTsdzb** [comment]
> Look good to me. Lint errors need to be ignored though?

Lint error fixed.

**Pull request merged**
