### PR TITLE
build: refine build workflow

### PR DESCRIPTION
**Pull request by shigma**
- Create `build.yml` for all build jobs
- `on` do not enforce `main` branch
- Drop Node.js 16
- Do not `fail-fast`
- Only enable `matrix` on tests
- Add a standalone `build` job

### CODE REVIEW

**Review by MaikoTan — COMMENTED** [review]
Overall I like the idea here. But I saw there are steps `checkout` `setup-node` and `cache` every where, can it be done by a composite action (let's say `prepare`) to do all the things without duplicating them every time?

**Comment by shigma** [comment]
> Overall I like the idea here. But I saw there are steps `checkout` `setup-node` and `cache` every where, can it be done by a composite action (let's say `prepare`) to do all the things without duplicating them every time?

Of course it can, but I'm afraid this could not save much time because the time consumed by `checkout` + `setup-node` + `cache` is no less than the time consumed by job setup.

**Comment by MaikoTan** [comment]
> Of course it can, but I'm afraid this could not save much time because the time consumed by `checkout` + `setup-node` + `cache` is no less than the time consumed by job setup.

Well, I am not worrying about the time consuming, but the duplication of the steps. I think the `composite actions` can be also used for other repositories in the future.

**Comment by shigma** [comment]
> Well, I am not worrying about the time consuming, but the duplication of the steps. I think the `composite actions` can be also used for other repositories in the future.

Oh you mean the composite actions, not job reusing. I think composite actions should belong to in another repository and is not relavent to this PR (I have no idea how to write such actions either).

**Comment by MaikoTan** [comment]
> Oh you mean the composite actions, not job reusing. I think composite actions should belong to in another repository and is not relavent to this PR (I have no idea how to write such actions either).

Oh, I could do it later, for now I would merge this PR first.

**Review by MaikoTan — APPROVED** [review]
LGTM. Let's give it a fly!

**Pull request merged**
